### ISSUE TITLE
Import augur auto-generated API docs

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/docs.nextstrain.org#10]
This is a progress-tracker type issue to track the incorporation of augur auto-generated API documentation which is currently rendered at https://docs.nextstrain.org/projects/augur/en/stable/api/api.html.

I believe we want to use [read the docs subprojects](https://docs.readthedocs.io/en/stable/subprojects.html) for in order to have versioned documentation -- e.g.preserve the API docs for each different augur version & access it via a URL.

**Comment by eharkins** [comment]
Oops, the commit message there is supposed to say "naive first attempt not using ~~submodules~~ subprojects". I'm hoping my first approach will mesh well with recognizing the augur submodule version using a subproject, i.e. #12 is possible in a way that allows you to control the hierarchy of subproject documents within the parent project.

**Comment by eharkins** [comment]
https://github.com/nextstrain/docs.nextstrain.org/commit/a1572138d22300a37163c6682c206147c1b6c38b changes the reference/augur heading in the sidebar to a link to https://docs.nextstrain.org/projects/augur/en/migrate-docs/index.html, where all augur reference documents have been consolidated into the augur subproject (and all non-reference documents are not listed / rendered in the subproject or its sidebar since they are instead imported via the git submodule and listed / rendered in the main project).

**Comment by eharkins** [comment]
This is done for now using subprojects. If #27 pans out, there will be some work again here to change implementation of including these docs so that they show up in this project's table of contents / sidebar instead of having to navigate to a separate url to get to the augur subproject.
