### ISSUE TITLE
Add note about how to symlink to Windows storage from Linux in WSL installation guide

### ISSUE THREAD

**Issue by huddlej** [nextstrain/docs.nextstrain.org#114]
Following up on [a year-old Slack conversation](https://bedfordlab.slack.com/archives/C01LCTT7JNN/p1624641884179500), we should provide instructions for users who run Linux in WSL on Windows to link their Windows storage from Linux in a standard way. This approach allows users to use the Windows explorer interface to manage files instead of the Linux filesystem. A generic solution might be to map the top-level user directory from Windows to a standard name in the Linux filesystem like:

```bash
ln -s /mnt/c/Users/<user> ~/windows_user
```

We should clarify that the `<user>` that users enter here is their _Windows_ username and not the Linux username, since these names can be different.

**Comment by huddlej** [comment]
Other alternate names for the target of the link are welcome! @j23414 suggested "HOME".

**Comment by tsibley** [comment]
Is manipulating the files from within Windows likely to cause issues with line endings? I guess it depends on the editor…

**Comment by emmahodcroft** [comment]
> Is manipulating the files from within Windows likely to cause issues with line endings? I guess it depends on the editor…

It depends on the editor I think. Mostly I think the recent issue was because the person was using git on the Windows side - I'd suggest using git in WSL If you are using WSL. Personally, I run everything (and `git` everything) in WSL but edit files through Visual Studio on Windows, and the only "trouble" I've had with line ending is (sometimes, rarely) git changes that include changing one line ending for the other

> Other alternate names for the target of the link are welcome!
As a Windows user, I would find a folder called `windows_user` kind of weird. This feels like it might be some kind of Windows system folder, maybe. I think `Home` or `wsl_home` might work better. I personally use `wsl` as a reminder that this is why these files are here (as opposed to elsewhere) -- stuff that I'm running in WSL.

Also worth repeating that there's no actual division between file storage or drive division with WSL/Windows -- it's mostly just that it's a real pain to get to the Linux filespace - it's buried deep in Windows and almost impossible to find. But you can run files anywhere on the drive as long as you're in the right place (or have the right path). This is very non-intuitive to Windows users and since you don't _need_ to be in that Linux space, it's easier to just make a folder you can quickly `cd` into and also easily access through the file explorer. 
_(Though one big warning here is that one should never edit system files from either OS in the other OS - always edit Unix files in Linux & Windows files in Windows)_


Finally, if we add something to docs, we should include double-checking what your actual file path is in the file explorer system. The above command (and what we used to have, before docs rewrite) fails spectacularly if your OS language isn't English and 'Users' isn't 'Users'.... 🙃  (In German: "Benutzer")

**Comment by tsibley** [comment]
Thanks for all that info/experience, @emmahodcroft!

One place I think I've noticed line endings going a bit wonky even in our repos is when new files are introduced from Windows (as opposed to edits to existing files which were introduced from Unix). Most editors these days will detect and match the line endings of an existing file (unlike the bad old days, and who knows, maybe still Notepad doesn't?), but when creating a new file, most editors (IME) will still use the default line endings for the system/platform they're running on. I worry this might cause issues, but the answer may also be "make our tools handle different line endings better if they don't already".

> The above command (and what we used to have, before docs rewrite) fails spectacularly if your OS language isn't English and 'Users' isn't 'Users'.... upside_down_face (In German: "Benutzer")

There a several mechanisms for obtaining the correct path here programmatically. For example, there are environment variables, at least in the Windows console world though not sure about within WSL. So we could craft a command that'd actually be portable (though a bit more opaque maybe).

**Comment by victorlin** [comment]
> As a Windows user, I would find a folder called `windows_user` kind of weird. This feels like it might be some kind of Windows system folder, maybe. I think `Home` or `wsl_home` might work better. I personally use `wsl`

This kind of thing might be better phrased as an example to customize (of course, we can still debate the example name):

---

The following command will make your Windows home directory accessible under your WSL home directory as a folder `windows_user`. This allows you to use Windows-based text editors and Linux commands all on the same files. Before running,

1. Replace `<user>` with your Windows username.
2. Optionally, change the `windows_user` folder name or only link to a specific directory under your windows user  (e.g. `ln -s /mnt/c/Users/<user>/Documents ~/windows_documents`).

```sh
ln -s /mnt/c/Users/<user> ~/windows_user
```

**Comment by victorlin** [comment]
Someone at the Bloom lab retreat Nextstrain workshop was confused how to access Windows files from WSL, and reminded me that I never got around to creating a PR here. Doing that now.
