### ISSUE TITLE
Numbered list starting not at zero in markdown document

### ISSUE THREAD

**Issue by eharkins** [nextstrain/docs.nextstrain.org#5]
Small bug where the numbered list on https://nextstrain.github.io/ncov/ starts over again at 1 when rendered in read the docs: 
 https://docs.nextstrain.org/en/migrate/ncov/docs/index.html

This is not significant enough to stop this project from going into production in my opinion.

I couldn't find any immediate solutions to this problem as it exists in the above example without indenting the content that breaks up the numbered list.

**Comment by victorlin** [comment]
Noting that this issue is describing behavior of ncov docs, which is now sourced from [nextstrain/ncov/docs](https://github.com/nextstrain/ncov/blob/338e07e0c393f1288da3be61ebce6bca2d7d0ed4/docs). Also the temp links in the original issue are outdated.

Lists are used pretty heavily in the tutorials, and they all behave as expected. An example ([src](https://github.com/nextstrain/ncov/blob/338e07e0c393f1288da3be61ebce6bca2d7d0ed4/docs/src/tutorial/custom-data.rst?plain=1#L14-L15)) ([temp link](https://docs.nextstrain.org/projects/ncov/en/latest/tutorial/custom-data.html#prerequisites)):

![image](https://user-images.githubusercontent.com/13424970/183495084-cf394323-f691-4f8c-b80e-a6eba1910eb3.png)

Closing since I don't see any mis-numbered lists there.
