### ISSUE TITLE
Including an External Document Fragment

### ISSUE THREAD

**Issue by eharkins** [nextstrain/docs.nextstrain.org#6]
Just surfacing some docs, threads related to this subject which @jameshadfield and chatted about and thought might be useful.

1. [restructured text include statement](https://docutils.sourceforge.io/docs/ref/rst/directives.html#including-an-external-document-fragment)
2. [thread about how to use ^ to parse markdown document [fragments]](https://github.com/sphinx-doc/sphinx/issues/2840)

**Comment by victorlin** [comment]
I believe this has been solved since we are actively using the `include` directive:

https://github.com/nextstrain/docs.nextstrain.org/blob/b74453593fa9793abc6ea73c3aebd6fe3c34d93a/src/install.rst#L120

There hasn't been a need to use `include` with markdown documents, but the 2nd link in the issue description could be useful if that need ever arises.
